# Generated by Django 6.0.6 on 2026-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='esp32-001', max_length=100, unique=True)),
                ('opto_pin', models.IntegerField(default=0)),
                ('pressure_status', models.CharField(choices=[('normal', 'Pressure Normal'), ('low', 'Pressure Low')], default='normal', max_length=20)),
                ('device_state', models.CharField(choices=[('off', 'OFF'), ('on', 'ON')], default='off', max_length=20)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
