# Generated by Django 6.0.6 on 2026-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='device_state',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('off', 'OFF'), ('on', 'ON')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='opto_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='pressure_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('normal', 'Pressure Normal'), ('low', 'Pressure Low')], default='unknown', max_length=20),
        ),
    ]
