# Generated by Django 6.0.6 on 2026-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0002_alter_devicestatus_device_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='mqtt_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='relay_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
