# Generated by Django 6.0.6 on 2026-06-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0005_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='esp32-001', max_length=100)),
                ('action', models.CharField(choices=[('on', 'Turned ON'), ('off', 'Turned OFF')], max_length=10)),
                ('source', models.CharField(choices=[('dashboard', 'Dashboard'), ('physical_button', 'Physical Button'), ('system', 'System')], default='dashboard', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_full_name', models.CharField(blank=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
